-- Auto-generated seed data mirroring server/src/game/challenges.ts (kept in sync by hand;
-- if you edit one, edit the other, or regenerate this file from that source).

insert into categories (id, label, sort_order) values
  ('animals', 'Animals', 0),
  ('vehicles', 'Vehicles', 1),
  ('technology', 'Technology', 2),
  ('household', 'Household', 3),
  ('funny', 'Funny', 4),
  ('monsters', 'Monsters', 5),
  ('human', 'Human', 6)
on conflict (id) do nothing;

insert into challenges (id, name, category_id, difficulty, audio_path, duration_seconds, tags, emoji) values
  ('an-cat', 'Cat', 'animals', 1, 'animals/cat.mp3', 2, '{"meow"}', '🐱'),
  ('an-dog', 'Dog', 'animals', 1, 'animals/dog.mp3', 2, '{"bark"}', '🐶'),
  ('an-cow', 'Cow', 'animals', 1, 'animals/cow.mp3', 3, '{"moo"}', '🐄'),
  ('an-duck', 'Duck', 'animals', 1, 'animals/duck.mp3', 2, '{"quack"}', '🦆'),
  ('an-monkey', 'Monkey', 'animals', 2, 'animals/monkey.mp3', 2, '{"ooh-ooh"}', '🐵'),
  ('an-lion', 'Lion', 'animals', 2, 'animals/lion.mp3', 3, '{"roar"}', '🦁'),
  ('an-wolf', 'Wolf', 'animals', 2, 'animals/wolf.mp3', 3, '{"howl"}', '🐺'),
  ('an-horse', 'Horse', 'animals', 2, 'animals/horse.mp3', 2, '{"neigh"}', '🐴'),
  ('an-elephant', 'Elephant', 'animals', 3, 'animals/elephant.mp3', 3, '{"trumpet"}', '🐘'),
  ('an-rooster', 'Rooster', 'animals', 1, 'animals/rooster.mp3', 2, '{"crow"}', '🐓'),
  ('ve-car', 'Car Engine', 'vehicles', 1, 'vehicles/car.mp3', 3, '{"vroom"}', '🚗'),
  ('ve-motorcycle', 'Motorcycle', 'vehicles', 2, 'vehicles/motorcycle.mp3', 3, '{"revving"}', '🏍️'),
  ('ve-train', 'Train', 'vehicles', 2, 'vehicles/train.mp3', 3, '{"chugga"}', '🚂'),
  ('ve-airplane', 'Airplane', 'vehicles', 2, 'vehicles/airplane.mp3', 3, '{"jet"}', '✈️'),
  ('ve-boat', 'Boat', 'vehicles', 1, 'vehicles/boat.mp3', 3, '{"horn"}', '🚤'),
  ('ve-helicopter', 'Helicopter', 'vehicles', 3, 'vehicles/helicopter.mp3', 3, '{"chop"}', '🚁'),
  ('ve-truck', 'Truck Horn', 'vehicles', 1, 'vehicles/truck.mp3', 2, '{"honk"}', '🚚'),
  ('ve-bicyclebell', 'Bicycle Bell', 'vehicles', 1, 'vehicles/bicyclebell.mp3', 1, '{"ring"}', '🚲'),
  ('ve-ambulance', 'Ambulance Siren', 'vehicles', 3, 'vehicles/ambulance.mp3', 3, '{"siren"}', '🚑'),
  ('ve-rocket', 'Rocket Launch', 'vehicles', 3, 'vehicles/rocket.mp3', 3, '{"blastoff"}', '🚀'),
  ('te-oldpc', 'Old Computer Startup', 'technology', 2, 'technology/oldpc.mp3', 3, '{"boot"}', '🖥️'),
  ('te-notification', 'Notification Sound', 'technology', 1, 'technology/notification.mp3', 1, '{"ping"}', '🔔'),
  ('te-robot', 'Robot Voice', 'technology', 2, 'technology/robot.mp3', 2, '{"beep-boop"}', '🤖'),
  ('te-printer', 'Printer', 'technology', 2, 'technology/printer.mp3', 3, '{"whirr"}', '🖨️'),
  ('te-modem', 'Dial-up Modem', 'technology', 3, 'technology/modem.mp3', 3, '{"screech"}', '📠'),
  ('te-keyboard', 'Mechanical Keyboard', 'technology', 1, 'technology/keyboard.mp3', 2, '{"clack"}', '⌨️'),
  ('te-camera', 'Camera Shutter', 'technology', 1, 'technology/camera.mp3', 1, '{"click"}', '📷'),
  ('te-phone', 'Old Phone Ring', 'technology', 2, 'technology/phone.mp3', 2, '{"ring"}', '☎️'),
  ('te-drone', 'Drone', 'technology', 2, 'technology/drone.mp3', 3, '{"buzz"}', '🛸'),
  ('te-lowbattery', 'Low Battery Beep', 'technology', 1, 'technology/lowbattery.mp3', 1, '{"beep"}', '🔋'),
  ('ho-vacuum', 'Vacuum Cleaner', 'household', 1, 'household/vacuum.mp3', 3, '{"hum"}', '🧹'),
  ('ho-doorbell', 'Doorbell', 'household', 1, 'household/doorbell.mp3', 1, '{"ding-dong"}', '🔔'),
  ('ho-alarm', 'Alarm Clock', 'household', 1, 'household/alarm.mp3', 2, '{"beeping"}', '⏰'),
  ('ho-blender', 'Blender', 'household', 2, 'household/blender.mp3', 3, '{"whir"}', '🧃'),
  ('ho-washingmachine', 'Washing Machine', 'household', 2, 'household/washingmachine.mp3', 3, '{"spin"}', '🧺'),
  ('ho-kettle', 'Boiling Kettle', 'household', 2, 'household/kettle.mp3', 3, '{"whistle"}', '🫖'),
  ('ho-microwave', 'Microwave Beep', 'household', 1, 'household/microwave.mp3', 1, '{"beep"}', '📻'),
  ('ho-toaster', 'Toaster Pop', 'household', 1, 'household/toaster.mp3', 1, '{"pop"}', '🍞'),
  ('ho-creakydoor', 'Creaky Door', 'household', 2, 'household/creakydoor.mp3', 2, '{"creak"}', '🚪'),
  ('ho-clock', 'Ticking Clock', 'household', 1, 'household/clock.mp3', 3, '{"tick-tock"}', '🕰️'),
  ('fu-cartoonlaugh', 'Cartoon Laugh', 'funny', 1, 'funny/cartoonlaugh.mp3', 2, '{"haha"}', '😂'),
  ('fu-confused', 'Confused Person', 'funny', 2, 'funny/confused.mp3', 2, '{"huh"}', '🤨'),
  ('fu-sneeze', 'Sneeze', 'funny', 1, 'funny/sneeze.mp3', 1, '{"achoo"}', '🤧'),
  ('fu-scream', 'Dramatic Scream', 'funny', 2, 'funny/scream.mp3', 2, '{"ahh"}', '😱'),
  ('fu-tinyvoice', 'Tiny Voice', 'funny', 2, 'funny/tinyvoice.mp3', 2, '{"squeak"}', '🐭'),
  ('fu-babytalk', 'Baby Talk', 'funny', 2, 'funny/babytalk.mp3', 2, '{"goo-goo"}', '👶'),
  ('fu-evillaugh', 'Evil Laugh', 'funny', 2, 'funny/evillaugh.mp3', 2, '{"muahaha"}', '😈'),
  ('fu-hiccup', 'Hiccup', 'funny', 1, 'funny/hiccup.mp3', 1, '{"hic"}', '😵'),
  ('fu-yawn', 'Big Yawn', 'funny', 1, 'funny/yawn.mp3', 2, '{"ahh-hmm"}', '🥱'),
  ('fu-nervouslaugh', 'Nervous Laugh', 'funny', 2, 'funny/nervouslaugh.mp3', 2, '{"heh"}', '😅'),
  ('mo-alien', 'Alien', 'monsters', 3, 'monsters/alien.mp3', 2, '{"blip"}', '👽'),
  ('mo-growl', 'Monster Growl', 'monsters', 2, 'monsters/growl.mp3', 2, '{"grr"}', '👹'),
  ('mo-zombie', 'Zombie', 'monsters', 2, 'monsters/zombie.mp3', 2, '{"groan"}', '🧟'),
  ('mo-roar', 'Creature Roar', 'monsters', 3, 'monsters/roar.mp3', 2, '{"roar"}', '🦖'),
  ('mo-ghost', 'Ghost', 'monsters', 2, 'monsters/ghost.mp3', 2, '{"ooooh"}', '👻'),
  ('mo-witch', 'Witch Cackle', 'monsters', 2, 'monsters/witch.mp3', 2, '{"cackle"}', '🧙'),
  ('mo-vampire', 'Vampire Hiss', 'monsters', 2, 'monsters/vampire.mp3', 2, '{"hiss"}', '🧛'),
  ('mo-goblin', 'Goblin', 'monsters', 2, 'monsters/goblin.mp3', 2, '{"cackle"}', '👺'),
  ('mo-kraken', 'Sea Monster', 'monsters', 3, 'monsters/kraken.mp3', 3, '{"roar"}', '🐙'),
  ('mo-werewolf', 'Werewolf Howl', 'monsters', 3, 'monsters/werewolf.mp3', 2, '{"howl"}', '🐺'),
  ('hu-laugh', 'Laugh', 'human', 1, 'human/laugh.mp3', 2, '{"haha"}', '😆'),
  ('hu-cry', 'Cry', 'human', 2, 'human/cry.mp3', 2, '{"sob"}', '😢'),
  ('hu-whistle', 'Whistle', 'human', 2, 'human/whistle.mp3', 2, '{"tune"}', '😗'),
  ('hu-snore', 'Snore', 'human', 1, 'human/snore.mp3', 2, '{"zzz"}', '😴'),
  ('hu-cough', 'Cough', 'human', 1, 'human/cough.mp3', 1, '{"ahem"}', '🤒'),
  ('hu-gasp', 'Gasp', 'human', 1, 'human/gasp.mp3', 1, '{"gasp"}', '😮'),
  ('hu-burp', 'Burp', 'human', 1, 'human/burp.mp3', 1, '{"urp"}', '🫃'),
  ('hu-whisper', 'Whisper', 'human', 3, 'human/whisper.mp3', 2, '{"shh"}', '🤫'),
  ('hu-humming', 'Humming', 'human', 2, 'human/humming.mp3', 2, '{"hmm"}', '🎵'),
  ('hu-clap', 'Clapping', 'human', 1, 'human/clap.mp3', 2, '{"clap"}', '👏')
on conflict (id) do nothing;

